In [48]:
import numpy as np
%matplotlib inline

In [49]:
nd_arr1 = np.array([[1, 2, 3], [2, 3, 4]])
print(nd_arr1)

[[1 2 3]
 [2 3 4]]


In [50]:
nd_arr2 = np.ones(shape=(3,2))
print(nd_arr2)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [51]:
nd_arr3 = np.empty(shape=(3,2))
print(nd_arr3)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [52]:
nd_arr4 = np.eye(3, 2)
print(nd_arr4)

[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]]


In [53]:
nd_arr5 = np.arange(6)
print(nd_arr5)
nd_arr5 = np.arange(6).reshape(3, 2)
print(nd_arr5)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [54]:
names = np.array(['Bob', 'Joe', 'Bob'])
nd_arr5[names == 'Bob']

array([[0, 1],
       [4, 5]])

In [57]:
nd_arr5[nd_arr5 < 3] = 0
print(nd_arr5)

[[0 0]
 [0 3]
 [4 5]]
